<a href="https://colab.research.google.com/github/venkatasaiaitha-dotcom/project2/blob/main/DA%26V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
df=pd.read_csv('Dav.csv')
df.head(10)

,ID No,Prog Code,Gender,YoG,CGPA,CGPA100,CGPA200,CGPA300,CGPA400,SGPA
0,42308,ICE,Female,2010,3.23,2.88,3.48,2.62,2.90,3.13
1,70978,BCH,Female,2010,3.58,3.25,4.26,3.37,3.47,3.02
2,31602,BCH,Male,2010,2.21,1.78,1.98,1.49,2.51,2.19
3,63847,BCH,Male,2010,2.70,2.67,2.44,2.00,2.35,3.19
4,30158,BCH,Female,2010,3.88,3.61,3.69,3.63,4.58,4.24
5,51740,BCH,Male,2010,2.97,2.66,2.98,3.28,3.07,3.13
6,76075,BCH,Male,2010,3.34,3.68,3.00,3.44,3.28,3.02
7,60888,BCH,Female,2010,2.56,2.30,2.50,2.29,2.77,2.68
8,43378,BCH,Male,2010,3.76,3.30,3.64,3.88,4.37,3.13
9,80307,BCH,Female,2010,3.96,3.94,3.89,3.81,4.17,3.98

In [8]:
df.dtypes

ID No          int64
Prog Code     object
Gender        object
YoG            int64
CGPA         float64
CGPA100      float64
CGPA200      float64
CGPA300      float64
CGPA400      float64
SGPA         float64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3046 entries, 0 to 3045
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID No      3046 non-null   int64
 1   Prog Code  3046 non-null   object
 2   Gender     3046 non-null   object
 3   YoG        3046 non-null   int64
 4   CGPA       3046 non-null   float64
 5   CGPA100    3046 non-null   float64
 6   CGPA200    3046 non-null   float64
 7   CGPA300    3046 non-null   float64
 8   CGPA400    3046 non-null   float64
 9   SGPA       3046 non-null   float64
dtypes: float64(6), int64(2), object(2)
memory usage: 238.1+ KB

In [10]:
df.isnull().sum()

ID No        0
Prog Code    0
Gender       0
YoG          0
CGPA         0
CGPA100      0
CGPA200      0
CGPA300      0
CGPA400      0
SGPA         0
dtype: int64

In [20]:
df['ID No'] #This is called series

0       42308
1       70978
2       31602
3       63847
4       30158
        ...
3041    64106
3042    96596
3043    64982
3044    27052
3045    65054
Name: ID No, Length: 3046, dtype: int64

In [23]:
df[['ID No','Prog Code','Gender']]

      ID No Prog Code  Gender
0     42308       ICE  Female
1     70978       BCH  Female
2     31602       BCH    Male
3     63847       BCH    Male
4     30158       BCH  Female
...     ...       ...     ...
3041  64106      PHYG  Female
3042  96596      PHYG    Male
3043  64982      PHYG    Male
3044  27052      PHYG  Female
3045  65054      PHYG    Male

[3046 rows x 3 columns]

In [13]:
df.iloc[9]

ID No         80307
Prog Code       BCH
Gender       Female
YoG            2010
CGPA           3.96
CGPA100        3.94
CGPA200        3.89
CGPA300        3.81
CGPA400        4.17
SGPA           3.98
Name: 9, dtype: object

In [14]:
df.iloc[0:12]

,ID No,Prog Code,Gender,YoG,CGPA,CGPA100,CGPA200,CGPA300,CGPA400,SGPA
0,42308,ICE,Female,2010,3.23,2.88,3.48,2.62,2.90,3.13
1,70978,BCH,Female,2010,3.58,3.25,4.26,3.37,3.47,3.02
2,31602,BCH,Male,2010,2.21,1.78,1.98,1.49,2.51,2.19
3,63847,BCH,Male,2010,2.70,2.67,2.44,2.00,2.35,3.19
4,30158,BCH,Female,2010,3.88,3.61,3.69,3.63,4.58,4.24
5,51740,BCH,Male,2010,2.97,2.66,2.98,3.28,3.07,3.13
6,76075,BCH,Male,2010,3.34,3.68,3.00,3.44,3.28,3.02
7,60888,BCH,Female,2010,2.56,2.30,2.50,2.29,2.77,2.68
8,43378,BCH,Male,2010,3.76,3.30,3.64,3.88,4.37,3.13
9,80307,BCH,Female,2010,3.96,3.94,3.89,3.81,4.17,3.98
10,82483,BCH,Female,2010,3.99,3.83,4.06,3.56,4.40,4.11
11,40021,BCH,Male,2010,3.02,2.94,3.02,3.00,3.13,2.92

In [24]:
df.loc[0,['ID No','Prog Code','Gender']]

ID No         42308
Prog Code       ICE
Gender       Female
Name: 0, dtype: object

In [25]:
df['ID No'].dtypes

dtype('int64')

In [26]:
df['Prog Code'].dtypes

dtype('O')

In [30]:
meanVal=df['CGPA'].mean()
print(meanVal)

3.4948128693368354